#!/usr/bin/env node
// Assemble creation_ring.implicit.js from the parts.
//   node build_model.mjs                 -> creation_ring.implicit.js (everything)
//   node build_model.mjs band            -> test_band.implicit.js (one part, at the origin)
//   node build_model.mjs human_hand      -> test_human_hand.implicit.js (hand in its own frame)
//   node build_model.mjs robot_hand      -> test_robot_hand.implicit.js
import fs from 'node:fs';
import { P, handFrame, frameToLocalGLSL, Ri, rx, rz, Rc } from './parts/params.mjs';
import * as band from './parts/band.mjs';
import * as human from './parts/human_hand.mjs';
import * as robot from './parts/robot_hand.mjs';

const which = process.argv[2] || 'all';
const H = handFrame(+1), R = handFrame(-1);
const L = H.L;
const outer = Ri + P.bandT + 0.5;

let body, bounds, name, out;
if (which === 'all') {
  body = `${band.glsl()}\n${human.glsl(L)}\n${robot.glsl(L)}\n${frameToLocalGLSL('to_human', H)}\n${frameToLocalGLSL('to_robot', R)}
float sdf(vec3 p) {
  float b = band_sdf(p);
  float h = human_hand_sdf(to_human(p));
  float r = robot_hand_sdf(to_robot(p));
  return implicit_union_round(implicit_union_round(b, h, 1.0), r, 1.0);
}`;
  bounds = [[-outer, -outer, -0.7 * L], [outer, outer, rz + 1.5]];
  name = 'Creation Ring (implicit)'; out = 'creation_ring.implicit.js';
} else if (which === 'band') {
  body = `${band.glsl()}\nfloat sdf(vec3 p) { return band_sdf(p); }`;
  bounds = [[-outer, -outer, -rz - 0.5], [outer, outer, rz + 0.5]];
  name = 'band only'; out = 'test_band.implicit.js';
} else {
  const part = which === 'human_hand' ? human : robot;
  const needsEllipsoid = which === 'robot_hand' && !robot.glsl(L).includes('float sd_ellipsoid');
  body = `${needsEllipsoid ? human.glsl(L).split('float human_hand_sdf')[0] : ''}${part.glsl(L)}\nfloat sdf(vec3 p) { return ${which}_sdf(p); }`;
  bounds = [[-0.6 * L, -0.5 * L, -0.7 * L], [1.15 * L, 0.5 * L, 0.35 * L]];
  name = `${which} only`; out = `test_${which}.implicit.js`;
}
const src = `// GENERATED by build_model.mjs — edit parts/*.mjs instead.
export default {
  schema: "implicit.js/0.1.0",
  name: ${JSON.stringify(name)},
  units: "mm",
  bounds: ${JSON.stringify(bounds)},
  render: { steps: 256, epsilon: 0.003 },
  glsl: \`${body.replace(/`/g, '\\`')}\`,
};
`;
fs.writeFileSync(out, src);
console.log(`wrote ${out}  (hand length ${L.toFixed(2)} mm)`);
